### ISSUE TITLE
金钱不够 无法触发 显示金钱不够

### ISSUE THREAD

**Issue by MOMOas** [TrMenu/TrMenu#125]
- 'Tell: &c你金钱不足无法补血_||_Break:<Requirement: %vault_eco_balance% < 1000>'
      - 'TAKE-MONEY: 1000'
      - 'op: heal %player_name%'
      - 'TELL: &f已花了&b1000 &f元恢复血量'

在打字窗那 没显示金钱 不足无法补写

**Comment by Arasple** [comment]
已修复
