### ISSUE TITLE
TrMenu error

### ISSUE THREAD

**Issue by Sikatsu** [TrMenu/TrMenu#127]
Hey, I seem to get this error in the console: https://pastebin.com/xEegcdbD
Don't know as of why though..

**Comment by Tanguygab** [comment]
I remember having the same error earlier when configurating dynamic slots, and since they are clearly specified in the error, I guess it's related.
Can you send your menu?

**Comment by Sikatsu** [comment]
Configurating dynamic slots? I don't know which of my menu could be affected :x

**Comment by Tanguygab** [comment]
maybe a menu with an item set on multiples slots? or else, try to remove your menus one by one, reload, and check the console each time
