### ISSUE TITLE
输入捕获前若不关闭菜单则易崩服

### ISSUE THREAD

**Issue by NPBeta** [TrMenu/TrMenu#130]
1. 聊天栏捕获不存在此问题，但需手动关闭菜单后输入；
2. 告示牌捕获可能存在此问题，且菜单的刷新会覆盖掉告示牌界面；
3. 铁砧捕获确认存在此问题，客户端和服务端同步卡死，部分服务端堆栈跟踪稍后附上。

![image](https://user-images.githubusercontent.com/17808640/89425346-773a3f80-d76b-11ea-86c4-158cad0971aa.png)
![image](https://user-images.githubusercontent.com/17808640/89425426-90db8700-d76b-11ea-9f09-eed801e8a24d.png)
![image](https://user-images.githubusercontent.com/17808640/89425532-b7012700-d76b-11ea-924a-751abd7b3c88.png)
![image](https://user-images.githubusercontent.com/17808640/89425607-cc765100-d76b-11ea-8c7b-9a3e3eb53a66.png)
![image](https://user-images.githubusercontent.com/17808640/89425645-d6984f80-d76b-11ea-88a9-98b116cc735a.png)

**Comment by NPBeta** [comment]
强烈建议输入捕获前自动关闭菜单，因为在几乎所有的情况下，这都是必要的一步操作以进行输入。

**Comment by Score2** [comment]
> 强烈建议输入捕获前自动关闭菜单，因为在几乎所有的情况下，这都是必要的一步操作以进行输入。

我认为应该由用户自己决定是否关闭菜单，假如我希望进入输入捕获状态还能再查看菜单一些提示信息再手动关闭菜单去输入内容，那么这个`自动关闭菜单`只会降低实用性。

应该是在文档里提醒用户，而不是强制。DeluxeMenus 最失败的原因就是因为太多鸡肋的设定而降低了实用性。

**Comment by NPBeta** [comment]
> 应该是在文档里提醒用户，而不是强制。DeluxeMenus 最失败的原因就是因为太多鸡肋的设定和强制的设定而降低了实用性。

支持，谢谢你的意见。将是否自动关闭菜单的选项留给服主或玩家确实是更好的选择。

**Comment by Arasple** [comment]
告示牌 & 铁砧的捕获器应该自动关闭菜单, 这个问题也解决了.
如果需要延时， 可以给 Catcher 动作设置 Delay 选项

**Comment by NPBeta** [comment]
> 请测试最新构建，此问题是否解决

已确认解决，感谢。
