### ISSUE TITLE
Language error?

### ISSUE THREAD

**Issue by Sikatsu** [TrMenu/TrMenu#134]
The plugin works fine, but on startup I have this error:

[23:57:42 INFO]: [TabooLib][ERROR] Error occureed when loading language for TrMenu: java.util.ConcurrentModificationException
java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1680)

TrMenu 2.0.1

**Comment by Arasple** [comment]
Delete the `plugins/TrMenu/lang` to regenerate to fix this :)

**Comment by Sikatsu** [comment]
I did once you asked, and now it's back..
