### ISSUE TITLE
Taboolib errors

### ISSUE THREAD

**Issue by Sikatsu** [TrMenu/TrMenu#135]
Another error, I honestly have no idea why and when it exactly pops up..

1. https://pastebin.com/7fqHp2DE
2. https://pastebin.com/gCjgvqc2
3. https://pastebin.com/BEJjybUk

TrMenu 2.0.1

**Comment by Sikatsu** [comment]
I have another error regarding Taboolib: https://pastebin.com/BEJjybUk

**Comment by Arasple** [comment]
Hello, I need more detailed information so that I may reproduce it

What's your server version and which plugins are you using?

**Comment by Sikatsu** [comment]
I am not sure when these errors occur, but it also happens on TrMenu 2.0.2 and on paper 1.16.1 ^^

**Comment by Tanguygab** [comment]
I see that you are using CMI, and you have an error with a hook.
I guess you are using the recompiled version of Vault to support CMI. 
Maybe that is the problem?
Try with the normal Vault plugin, maybe it will fix those errors aswell as the economy actions one

**Comment by Sikatsu** [comment]
I am indeed using the recompiled version of Vault, which works with all plugins normally..

**Comment by Sikatsu** [comment]
And these taboolib errors also happen on my lobby, creative and event server. They do not have any economy at all

**Comment by Arasple** [comment]
Hello, please delete `libs/TabooLib.jar` and restart your server to update TabooLib
If further errors still occurred please post it here

Thanks 🙂

**Comment by Bkm016** [comment]
十分抱歉，因开发环境不同没有办法复现这个报错，只能根据特征进行 ”测试性“ 的修复。
有关 TabooLib 的漏洞可以在 https://github.com/taboolib/taboolib/issues 进行反馈，我们会及时修复。

**Comment by Sikatsu** [comment]
Now the whole plugin broke for me :s https://pastebin.com/m5Q7R7yf
