### ISSUE TITLE
Economy hook error

### ISSUE THREAD

**Issue by Sikatsu** [TrMenu/TrMenu#136]
This used to work fine on 2.0, but as of 2.0.1 this seems to be broken.

Error: https://pastebin.com/c7h7B0RD

Can not sell anything through menu's.

**Comment by Sikatsu** [comment]
Any news on this? @Arasple

**Comment by Arasple** [comment]
Hello, I need more detailed information so that I may reproduce it

What's your server version and which plugins are you using?

**Comment by Sikatsu** [comment]
I am not sure when these errors occur, but it also happens on TrMenu 2.0.2 and on paper 1.16.1 ^^
Plugins: https://pastebin.com/CTV19JXE

**Comment by Arasple** [comment]
Fixed in the latest commit
