### ISSUE TITLE
[IMPORTANT] Impossible to launch the plugin

### ISSUE THREAD

**Issue by TryToKnow** [TrMenu/TrMenu#139]
Server 1.8.8

Bungeecord : have internet
Spigot servers : all local

I download all libs and taboo.. but the plugin cant start !
https://pastebin.com/6qG6nqX0

I tryed everything, reload with plugman, restart but i cant launch TRHolograms or TRMenu..

**Comment by Galaxy-VN** [comment]
look like its a bug

**Comment by Arasple** [comment]
What's your JDK version?

**Comment by Arasple** [comment]
Please change to JDK 8 instead
