### ISSUE TITLE
客户端闪退

### ISSUE THREAD

**Issue by SeemWind** [TrMenu/TrMenu#140]
点击TrMenu v2的默认菜单的任何地方（包括gui外）都会导致客户端弹出服务器
DecoderException : java.l ang.IndexDutOfBoundsException: readerIndex(0)
length(1) exceeds writerIndex(0): UnpooledslicedByteBuf(ridx: 0, widx: 0, cap: 0/0， unwrapped:
PooledUnsafeDirec tByteBuf(ridx: 2, widx: 2, cap: 384)) @ 1o.netty.handler.codec.Message ToMessageDecoder:98

**Comment by Arasple** [comment]
请通过售后群联系反馈
