### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Okan-SEREN** [TrMenu/TrMenu#143]
[message.txt](https://github.com/TrMenu/TrMenu/files/5081341/message.txt)

PlaceholderAPI v2.10.9
Server paperspigot 1.12.2
TrMenu v2.02

The server gives such an error when starting up and a menu does not open error

The plugins there is such a bug in version 2.03 of the extension.

[latest.log](https://github.com/TrMenu/TrMenu/files/5081348/latest.log)

**Comment by Okan-SEREN** [comment]
https://github.com/TrMenu/TrMenu/issues/144  same bug
I could not explain because my English is bad.

**Comment by Arasple** [comment]
Fixed. Download the latest build
