### ISSUE TITLE
Language error

### ISSUE THREAD

**Issue by Sikatsu** [TrMenu/TrMenu#145]
Hey, you advised me to delete the file and let it regenerate, but the error is still there:

[12:51:27 INFO]: [TabooLib][ERROR] Error occureed when loading language for TrMenu: java.util.ConcurrentModificationException
java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1680)

**Comment by Sikatsu** [comment]
Any news on this one? ^^

**Comment by Tanguygab** [comment]
I remember having a similar error, but when updating to TabooLib 3.56 (or something like that, the latest I mean) it disappeared 🤷 so...

**Comment by titidelaff** [comment]
So???

**Comment by Sikatsu** [comment]
Still happens on 5.36 TabooLib, just tested :/

**Comment by Arasple** [comment]
Will be fixed in v3.0
