### ISSUE TITLE
Title Hex RGB is so weird

### ISSUE THREAD

**Issue by NightPrimez** [TrMenu/TrMenu#151]
**Describe the bug**
When i'm put RGB Code in `Title:` then color RGB is so weird (but Name, Lore is work fine)

**Plugins**
 - TrMenu 2.03-DEV
 - PlaceholderAPI 2.10.9

**To Reproduce**
1. Add hex color in Title setting (ex. `&{00ff5e}` //Lime)

**Expected behavior**
It's should be a lime text color but it's displaying Yellow text color in title

**Screenshots**
![Bug](https://i.imgur.com/clxswUG.png)

**Environment(please complete the following information):**
 - OS: Window 10 Pro (tested on localhost)
 - JDK: 1.8.0_261

**Comment by Arasple** [comment]
Fixed
