### ISSUE TITLE
Add a menu option.

### ISSUE THREAD

**Issue by Score2** [TrMenu/TrMenu#160]
**Type**
* Update the placeholder in the icon immediately after opening the menu.

**Description**
After testing and reviewing the document, I found that only using "update" or "refresh" can update the placeholder in the icon, but frequent refreshing is likely to cause the server to lag.
If I want to refresh the placeholder only once when I open the menu, instead of refreshing frequently, then this feature is very necessary.

**Usage**
```
Title: ...
Layout:
- ...

Options:
  Open-Refresh: true

Buttons:
  ...
```

**Example**
None.

**Additional context**
None

**Comment by Arasple** [comment]
Try adding `reset` action in menu close actions

```YAML
Events:
  Close: 'reset'
```

**Comment by Score2** [comment]
> Try adding `reset` action in menu close actions
> 
> ```yaml
> Events:
>   Close: 'reset'
> ```

This seems achievable, but I prefer it to be refreshed when opened, because my menu is displayed by getting the items in the player's hand to open the menu. If the menu is closed and then refreshed, it is impossible to predict the player's next item.
