### ISSUE TITLE
Datas issue

### ISSUE THREAD

**Issue by TadiklCZE** [TrMenu/TrMenu#167]
**Describe the bug**
Hello, when I use set-data/set-meta it keeps wiping them from any reason. (I use it with Input Catcher)

**Server Software**
git-Paper-33d42c8e (MC: 1.12.2)

**Plugins**
 - TrMenu 2.03
 - PlaceholderAPI 2.10.6
 - Luckperms

**To Reproduce**
I just used Advanced Input Catcher configuration and after each catcher it wiped it data. I also tried to set data before the catcher, but it still was wiping.

**Comment by Tanguygab** [comment]
I've opened a similar issue right before and Arasple closed it, I guess he already fixed it
