### ISSUE TITLE
修改面板文件后部分玩家自动打开面板

### ISSUE THREAD

**Issue by Joket-abc** [TrMenu/TrMenu#170]
**Describe the bug**
修改面板文件后部分玩家自动打开面板.

**Server Software**
git-Paper-144 (MC: 1.16.2)

**Plugins**
 - TrMenu 2.03
 - PlaceholderAPI 2.10.10

**To Reproduce**
重现步骤:
1. 修改面板配置
2. 可能发生有玩家自动打开之前打开过的面板(不一定是被修改的面板，可能会开启其他的)

**Expected behavior**
玩家不会被自动开启面板.

**Screenshots**
无法通过截图表现.

**Environment(please complete the following information):**
 - OS: Windows Server 2019
 - JRE: 1.8.0_251

**Additional context**
none.

**Comment by Arasple** [comment]
Fixed, thanks for the report
