### ISSUE TITLE
修改面板后图标显示异常

### ISSUE THREAD

**Issue by Joket-abc** [TrMenu/TrMenu#171]
**Describe the bug**
当有两个人同时打开同一面板时, 后台修改面板触发自动重载，面板的图标会计算异常.

**Server Software**
git-Paper-144 (MC: 1.16.2)

**Plugins**
 - TrMenu 2.03
 - PlaceholderAPI 2.10.10

**To Reproduce**
1. 两个人打开同一面板
2. 后台修改面板触发自动重载
3. 两个人显示的图标异常

**Expected behavior**
图标应该正常显示.

**Screenshots**
（这里的测试不改变面板内容，比如添加空格后删除，只是为了触发自动重载）
[正常的状态](http://i2.tiimg.com/623703/5b2ca1fdf8b22ec2.png)
[第一次自动重载后](http://i2.tiimg.com/623703/99d5902c047cab4f.png)
[第二次自动重载后](http://i2.tiimg.com/623703/482f1b737ce9a606.png)

**Environment(please complete the following information):**
 - OS: Windows Server 2019
 - JRE: 1.8.0_251

**Additional context**
[如果有需要，这里提供此面板的内容](https://netcut.cn/4dvhcinfsvq0).

**Comment by Arasple** [comment]
Fixed, thanks for the report
