### ISSUE TITLE
玩家背包有物品, 开启面板后物品仍然显示

### ISSUE THREAD

**Issue by Joket-abc** [TrMenu/TrMenu#174]
**Describe the bug**
玩家背包有物品, 开启面板后物品仍然显示(之前2.03版本没有这个问题).

**Server Software**
git-Paper-144 (MC: 1.16.2)

**Plugins**
 - TrMenu 2.04-DEV
 - PlaceholderAPI 2.10.10

**To Reproduce**
1. 打开面板
2. 背包内的物品仍被显示

**Expected behavior**
背包内的物品应被隐藏.

**Screenshots**
[背包内物品](http://i1.fuimg.com/623703/5e64fa24b334767c.png)
[开启的面板未隐藏物品](http://i1.fuimg.com/623703/86533ba39fa6b4f4.png)
[正常面板应该是这样](http://i1.fuimg.com/623703/5e97038b127f4270.png)

**Environment(please complete the following information):**
 - OS: Windows Server 2019
 - JRE: 1.8.0_251

**Additional context**
none.

**Comment by Arasple** [comment]
请提供菜单配置

**Comment by Joket-abc** [comment]
> 请提供菜单配置

https://netcut.cn/4dvoq5lu5c80

**Comment by Arasple** [comment]
尝试最新版本
