### ISSUE TITLE
Meta dont work in material

### ISSUE THREAD

**Issue by titidelaff** [TrMenu/TrMenu#178]
**Describe the bug**
Meta dont work in material

**Server Software**
git-Paper-143 (MC: 1.16.2)

**Plugins**
 - TrMenu 2.04
 - PlaceholderAPI 2.10.9

**To Reproduce**
use a meta to set material

**Expected behavior**
Material set correctly.

**Screenshots**

**Comment by Tanguygab** [comment]
to add something related, Datas don't work either in the material, and metas don't work with `%trmenu_meta_<key>%` (it always return "null") but `%trmenu_data_<key>%` works

**Comment by titidelaff** [comment]
so i can use set-data instead of set-meta and its gona work?

**Comment by Tanguygab** [comment]
no it doesn't, it's just a another problem similar that I wanted to note so Arasple can fix it too

**Comment by titidelaff** [comment]
snif
