### ISSUE TITLE
在condition中placeholder解析顺序问题

### ISSUE THREAD

**Issue by Score2** [TrMenu/TrMenu#182]
**Describe the bug**
在condition中placeholder解析顺序问题

**Server Software**
git-Paper-0893de14 (MC: 1.16.2) (Implementing API 版本 1.16.2-R0.1-SNAPSHOT)

**Plugins**
 - TrMenu 2.04
 - PlaceholderAPI 2.10.9

**To Reproduce**
* 在actions中的condition，表达式预设为 %javascript_${script_name}%，假如meta script_name 为 test
* 控制台出现报错：[TrMenu] ERROR | 表达式 %javascript_{meta:script_name}% 无法编译, 请检查语法
* 本该先解析花括号变量，而不是%变量

**Expected behavior**
在actions中的condition，meta script_name 为 test，表达式：%javascript_${script_name}% 会先解析 %javascript_${script_name}% 再解析 ${script_name}。

**Screenshots**
无

**Environment(please complete the following information):**
 - OS: [e.g. Windows Server 2019]
 - JDK: [e.g.1.8.0_261]

**Additional context**
无

**Comment by Arasple** [comment]
js 条件表达式使用 meta 变量请按照这个格式

`'%javascript_' + '{meta:script_name}' + '%' == "yes"`

**Comment by Score2** [comment]
> js 条件表达式使用 meta 变量请按照这个格式
> 
> `'%javascript_' + '{meta:script_name}' + '%' == "yes"`

我试了一下，这样的格式是错的
