### ISSUE TITLE
插件初始化无法加载菜单

### ISSUE THREAD

**Issue by myktw** [TrMenu/TrMenu#183]
**Describe the bug**
第一次加载插件无法加载初始化菜单Example
`[02:26:55] [Server thread/INFO]: [TrMenu] ERROR | An error occurred when loading the menu Example.
[02:26:55] [Server thread/INFO]: Message: kotlin.collections.ArraysKt.maxOrNull([Ljava/lang/Comparable;)Ljava/lang/Comparable;
`

**Server Software**
CatServer-237b0d4

**Plugins**
 - TrMenu 2.04
 - PlaceholderAPI 2.9.2

**To Reproduce**
1. 加入插件重启无法加载菜单

**Expected behavior**

**Screenshots**
![QQ截图20200902023106](https://user-images.githubusercontent.com/35424096/91891940-6aeec700-ecc4-11ea-8f4b-d5382c96df33.png)

**Environment(please complete the following information):**
 - OS: [e.g. Windows Server 2019]
 - JDK: [e.g.1.8.0_261]

**Additional context**

**Comment by myktw** [comment]
和PokemonAPI插件冲突会调用PokemonAPI的lib而不是TabooLib的lib

**Comment by Arasple** [comment]
此问题不会修复，请联系 PokemonAPI 更新 kt 库到 1.4+

**Comment by MMotherFucker** [comment]
> 此问题不会修复，请联系 PokemonAPI 更新 kt 库到 1.4+

PokemonAPI已移除了Kotlin依赖,尽管如此,宝可梦服务器依旧无法正常运行TrMenu插件

ScreenShot:
https://s1.ax1x.com/2020/09/30/0KezX4.md.png
https://s1.ax1x.com/2020/09/30/0KmV1O.png
