### ISSUE TITLE
2.0.4 Server crash on startup

### ISSUE THREAD

**Issue by Sikatsu** [TrMenu/TrMenu#184]
**Describe the bug**
Seems the issue isn't actually fixed, the server still sometimes crashes on startup on 2.0.4:

https://pastebin.com/ASr0AdVQ

**Server Software**
git-Paper-175 (MC: 1.16.2)

**Plugins**
 - TrMenu 2.0.4
 - PlaceholderAPI 2.10.9

**Comment by Arasple** [comment]
Fixed
Please update TabooLib
