### ISSUE TITLE
2.0.4 Console Spaming when using command

### ISSUE THREAD

**Issue by abczyx22** [TrMenu/TrMenu#185]
Describe the bug
when i using /menu to open main menu, the console spaming

https://pastebin.com/4Y8K4Aa1

Server Software
spigot (1.12.2)

Plugins

-  TrMenu 2.0.4
-  PlaceholderAPI 2.10.9
- Protocollib 4.5.1

**Comment by Arasple** [comment]
If your server is offline-mode and uses SkinsRestorer, don't use `<head: ID>`, which requires a Minecraft profile name

https://trmenu.trixey.cc/menu/icons/display/material#skinsrestorer-heads

**Comment by Arasple** [comment]
If that's not your situation, try to set `Options.Skull-Mojang-API` true in settings.yml
