### ISSUE TITLE
无法打开面板

### ISSUE THREAD

**Issue by Joket-abc** [TrMenu/TrMenu#186]
**Describe the bug**
无法打开任何面板. 后台报错
[http://netcut.cn/4e12ndc5hir0](http://netcut.cn/4e12ndc5hir0)

**Server Software**
git-Paper-178 (MC: 1.16.2)

**Plugins**
 - TrMenu 2.04
 - PlaceholderAPI 2.10.9

**Environment(please complete the following information):**
 - OS: [Windows Server 2019]
 - JRE: [1.8.0_261]

**Comment by Arasple** [comment]
无法重现，请提供完整服务器运行日志
