### ISSUE TITLE
PlaceholderAPI-2.10.9 issue?

### ISSUE THREAD

**Issue by leoncp9** [TrMenu/TrMenu#196]
hi, when i use PlaceholderAPI-2.10.9 plugin i get this error in console
log:
https://pastebin.com/UDYk1tC5
with PlaceholderAPI-2.10.6 work
so how can is possible fix the issue with latest update of placeholderapi plugin?

**Comment by Tanguygab** [comment]
this is due to PlaceholderAPI 20.10.7 and above changing some methods which broke some plugins depending on those.
TrMenu was using those methods and broke, and since it isn't supported anymore, it won't be fixed in TrMenu v1.

You can either downgrade PlaceholderAPI to 2.10.6 or use TrMenu v2

**Comment by leoncp9** [comment]
ok
