### ISSUE TITLE
Trmenu command binding error

### ISSUE THREAD

**Issue by titidelaff** [TrMenu/TrMenu#198]
**Describe the bug**
When i use command binding nothing happen and i get an error in the console
https://pastebin.com/nPBj0q0U

**Server Software**
git-Paper-148 (MC: 1.16.2)

**Plugins**
 - TrMenu 2.05
 - PlaceholderAPI 2.10.9

**Comment by Arasple** [comment]
Delete all the files in `plugins/TabooLib/libs` and restart your server
