### ISSUE TITLE
Shift+左键物品可以将该物品放在菜单空白处并不消耗该物品，在菜单中点击该物品会消失

### ISSUE THREAD

**Issue by SueFox** [TrMenu/TrMenu#201]
Shift+左键物品可以将该物品放在菜单空白处并不消耗该物品，点击菜单中的这个物品会消失
![背包](https://user-images.githubusercontent.com/71171999/93667524-297a5c00-fab9-11ea-9377-6ee7483cf6ce.png)
![菜单](https://user-images.githubusercontent.com/71171999/93667553-67778000-fab9-11ea-9b0c-912d1ed5ef9e.png)

服务器核心：
git-Paper-1604 (MC: 1.12.2)

插件
 - TrMenu 2.05
 - PlaceholderAPI 2.10.8

**Comment by Arasple** [comment]
无法复现

```
git-Paper-1618 (MC: 1.12.2)
TrMenu-2.05
PlaceholderAPI-2.10.10-DEV-109
```
