### ISSUE TITLE
By the way, may I ask about permissions

### ISSUE THREAD

**Issue by qwe938775** [TrMenu/TrMenu#204]
I updated to version 2.05
Friends don’t have permission to open the GUI interface
Which side must be modified or what permissions need to be added to them?

https://ibb.co/pbFtmPT

**Comment by qwe938775** [comment]
How to modify the middle button to open the page
Discord got no help
How do i have to add

Shortcuts:
  Offhand: 'open: Example'
  Sneaking-Offhand:
    - condition: 'hasPerm.trmenu.shortcut'
      execute: 'open: Example'
  Right-Click-Player: []
  Sneaking-Right-Click-Player: []
  PlayerInventory-Border-Left: []
  PlayerInventory-Border-Right: []
  PlayerInventory-Border-Middle: []

**Comment by Arasple** [comment]
Please refer to our wiki https://trmenu.trixey.cc/
