### ISSUE TITLE
Parameter specified as non-null is null

### ISSUE THREAD

**Issue by k88968896** [TrMenu/TrMenu#205]
**Describe the bug**
https://paste.in/fEVKtz

**Server Software**
git-Paper-387 (MC: 1.15.2)

**Plugins**
 - TrMenu 2.05
 - PlaceholderAPI 2.10.9

**To Reproduce**
我不太清楚我操了甚麼動作導致此問題發生
但大致上 我是在子圖標前加了一個# 然後reload
就導致問題發生了

**Expected behavior**
可以正確load menu

**Screenshots**
no

**Environment(please complete the following information):**
 - OS: Ubuntu 20.04
 - JDK: openjdk 1.8.0_262

**Additional context*

**Comment by Arasple** [comment]
如果你需要注释掉一个图标，请将整个图标的 YAML 节点注释

如果问题没得到解决，请提供菜单配置
