### ISSUE TITLE
title-update刷新时按钮也会跟着刷新

### ISSUE THREAD

**Issue by YsGqHY** [TrMenu/TrMenu#206]
**Describe the bug**

**Server Software**
git-Paper-137 (MC: 1.16.1)

**Plugins**
 - TrMenu 2.05
 - PlaceholderAPI 2.10.9

**To Reproduce**
1. ...

**Expected behavior**

**Screenshots**
https://s1.ax1x.com/2020/09/26/0PwNBd.gif

**Environment(please complete the following information):**
 - OS: [e.g. Windows Server 2019]
 - JDK: [e.g.1.8.0_261]

**Additional context**
title刷新时的闪烁，按钮也会跟着刷新而闪烁，导致某些奇怪的操作出现了

**Comment by qwe938775** [comment]
I have the same problem

**Comment by Arasple** [comment]
受原版所限，动态 TITLE 仅能通过重新发包打开一个容器实现，所有按钮都需要重新刷新

频闪问题目前已经尽力减小了 ，暂时无解决方案
