### ISSUE TITLE
Warn in console (heads)

### ISSUE THREAD

**Issue by Koudyasek** [TrMenu/TrMenu#216]
**Describe the bug**
Some warns in console

**To Reproduce**
1. When I'm open my menu /topstats, and the menu trying load heads, at first time doesn't load it, but if I wait 5seconds and then re-open it, no error more

**Screenshots**
https://pastebin.com/dqLj96qb

**Additional context**

**Server Information**
> Use command `/trmenu dump` to get the information
> Copy the information to below
e.g.
```
TrMenu Dump Information (2020-10-05 20:05:29)
https://hasteb.in/ayohewom

**Comment by Arasple** [comment]
Enable `Options.Skull-Mojang-API` in settings.yml
