### ISSUE TITLE
Gradient stopping issue

### ISSUE THREAD

**Issue by OfT3N** [TrMenu/TrMenu#221]
I was trying to add some gradient to the menu, but when i try to do it not for the whole text of the string, the gradient stops, but the ending {g} or {gradient} - doesn't dissappear 
![image](https://user-images.githubusercontent.com/62369973/97080321-28ca6d80-1603-11eb-90d4-53338dd957eb.png)
![image](https://user-images.githubusercontent.com/62369973/97080322-2ec04e80-1603-11eb-8275-25d135a86109.png)
![image](https://user-images.githubusercontent.com/62369973/97080325-34b62f80-1603-11eb-8017-91e93f9bf672.png)
![image](https://user-images.githubusercontent.com/62369973/97080327-38e24d00-1603-11eb-988e-f871295de74c.png)

**Comment by Arasple** [comment]
You can now use gradient in this way

`{#DA70D6}· {g:#4facfe:#00f2fe} TrMenu &8&k|&f {g:#43e97b:#38f9d7} Modern & Advanced Menu-Plugin`
