### ISSUE TITLE
Commands not wprking and throwing an error

### ISSUE THREAD

**Issue by OfT3N** [TrMenu/TrMenu#222]
The plugin throws an error when I try to open a menu by a command. Tried to define the command in different ways, nothing is changed.

https://hasteb.in/agurunil.sql - the error

https://hasteb.in/ajacotij - the TrMenu dump

![image](https://user-images.githubusercontent.com/62369973/97083770-13f9d400-161b-11eb-8233-c7f5dc77dfa4.png) - the menu config

**Comment by Arasple** [comment]
Show me what files are in `plugins/TabooLib/libs`

**Comment by Arasple** [comment]
Do you have any idea which plugins could be using Kotlin?

**Comment by OfT3N** [comment]
![image](https://user-images.githubusercontent.com/62369973/97084226-4f49d200-161e-11eb-8f55-a3138b5409c8.png)

**Comment by OfT3N** [comment]
Not sure about kotlin tbh
