### ISSUE TITLE
RGB in title messages issue

### ISSUE THREAD

**Issue by OfT3N** [TrMenu/TrMenu#226]
**Describe the bug**
When trying to send titlemsg from the menu, HEX colors doesnt work

**To Reproduce**
1. Just send an RGB title 

**Expected behavior**
Working RGB colors :/ as if i use it as command in CMI - RGB in titles works properly

**Screenshots**
![image](https://user-images.githubusercontent.com/62369973/97282898-4a6c6480-1850-11eb-9fa0-74eafd9dc330.png)

**Server Information**
https://hasteb.in/agiquqiw

**Comment by Arasple** [comment]
Will be supported in the next TabooLib update
