### ISSUE TITLE
HEX Codes don't work in functions to variables

### ISSUE THREAD

**Issue by MrWardy** [TrMenu/TrMenu#228]
**Describe the bug**
HEX codes do not seem to work when being put into a variable from a function to be used elsewhere in the menu.

**To Reproduce**
1. Create a function to change something like an icon title
2. Add a hex code to that title

**Expected behavior**
HEX codes should work from functions.

**Screenshots**
https://pastebin.com/u9T3nJ9Q <-- Code
The output for the first if else is "<<{######}Servus>>" in all gray, normal Minecraft codes work however the new hex codes do not

**Additional context**

**Server Information**
> Use command `/trmenu dump` to get the information
> Copy the information to below
e.g.
```
TrMenu Dump Information (2020-10-05 20:05:29)

| Server OS: Windows 10 amd64 10.0
| Server software: git-Tuinity-"88a2c88" (MC: 1.16.3) (1.16.3-R0.1-SNAPSHOT)
| Java version: 1.8.0_261

| TabooLib: 5.37
| TrMenu: 2.06-DEV / Tue Oct 06 04:03:33 CST 2020 (Built by Arasple)

Installed Plugins: 
· Adyeshach - 1.0.3 ALPHA
· Aide - 1.0-SNAPSHOT
· LuckPerms - 5.1.93
· PlaceholderAPI - 2.10.9-DEV-92
· TrMenu - 2.06-DEV
```

**Comment by Arasple** [comment]
Use `rwp` function to translate color / variables in js
```
  condA:
    name: |-
      function condAName() {
        if (player.hasPermission("ranks.path.rome")) {
          return rwp("&7«{#69420f}Servus&7»");
        } else if (player.hasPermission("ranks.path.greece")) {
          return rwp("&7«{#69420f}Duolos&7»");
        } else if (player.hasPermission("ranks.path.japan")) {
          return rwp("&7«{#69420f}Dorei&7»");
        } else {
          return "&4Error: &cNo Path Selected";
        }
      }
      condA()
```
