### ISSUE TITLE
Lore line conditiong (Cache error)

### ISSUE THREAD

**Issue by TadiklCZE** [TrMenu/TrMenu#229]
**Describe the bug**
There is an error when you use multiple conditional lines in lore

**To Reproduce**
Make multiple buttons with multiple lines of lores with conditions (Conditions with PAPI)

Using trmenu 2.06-DEV (Latest artifact)
Server: Yatopia 1.16.3

Error: https://hastebin.com/pilasebafu.sql

**Comment by TadiklCZE** [comment]
Longer error:
https://hastebin.com/ovezajeqof.sql

**Comment by Arasple** [comment]
Please provide your menu configuration of this issue
