### ISSUE TITLE
[FEATURE] Global-Data set/use

### ISSUE THREAD

**Issue by YsGqHY** [TrMenu/TrMenu#242]
**Type**
action

**Description**
新增一个 全局数据的动作 即%trmenu_global_key%的变量
 set-global(rem-global)
全服玩家使用该key变量是显示同一变量值

**Usage**
你懂的！

**Example**
player1: %trmenu_global_key% == Arasple
player2: %trmenu_global_key% == Arasple

**Additional context**

**Comment by Arasple** [comment]
Will be added in v3
