### ISSUE TITLE
TrMenu tab complete and cause crash

### ISSUE THREAD

**Issue by amrhfy** [TrMenu/TrMenu#245]
Just happens today, dk why but it crashed my server

Here's the crash report
https://hastebin.com/yanaloweqa.apache

> I can't use any trmenu command at all

TrMenu Dump Information (2020-10-05 20:05:29)

| Server OS: Windows 10 amd64 10.0
| Server software: PaperSpigot (MC: 1.16.3) (1.16.3-R0.1-SNAPSHOT)
| Java version: 1.8.0_261

| TabooLib: 5.37
| TrMenu: 2.06-DEV / Tue Oct 06 04:03:33 CST 2020 (Built by Arasple)

**Comment by Arasple** [comment]
1. Stop your server
2. Delete `libs` & `plugins/TabooLib` folder
3. Download the latest artifact on Github and restart your server
