### ISSUE TITLE
Parse gradient from placeholder

### ISSUE THREAD

**Issue by OfT3N** [TrMenu/TrMenu#246]
If a placeholder returns some text tike {g:#FFFFFF:#FFFFFF}ImAnExampleText - the menu doesn't parse it as a gradient

![image](https://user-images.githubusercontent.com/62369973/100322914-0054db00-2fd6-11eb-9fcf-25537b6a4477.png)

I need it really much cuz i have some custom animations that are placeholders

**Comment by Flaimer2** [comment]
> If a placeholder returns some text tike {g:#FFFFFF:#FFFFFF}ImAnExampleText - the menu doesn't parse it as a gradient
> 
> ![image](https://user-images.githubusercontent.com/62369973/100322914-0054db00-2fd6-11eb-9fcf-25537b6a4477.png)
> 
> I need it really much cuz i have some custom animations that are placeholders

А почему нельзя использовать просто этот заполнитель: https://api.extendedclip.com/expansions/gradient/

**Comment by OfT3N** [comment]
> > If a placeholder returns some text tike {g:#FFFFFF:#FFFFFF}ImAnExampleText - the menu doesn't parse it as a gradient
> > ![image](https://user-images.githubusercontent.com/62369973/100322914-0054db00-2fd6-11eb-9fcf-25537b6a4477.png)
> > I need it really much cuz i have some custom animations that are placeholders
> 
> А почему нельзя использовать просто этот заполнитель: https://api.extendedclip.com/expansions/gradient/ и просто используем javascript.

Из-за ублюдского оформления данного плейсхолдера, в котором в {} нету даже #, и в текстовом редакторе такие цвета у меня не отображаются. Тем более, что в принципе плагин должен парсить градиент в своём синтаксисе, как это делают другие плагины

**Comment by Arasple** [comment]
```YAML
Options:
  Pre-Color: false
```
