### ISSUE TITLE
#246 Solution doesn't work

### ISSUE THREAD

**Issue by OfT3N** [TrMenu/TrMenu#250]
**Describe the bug**
I put Pre-Color: false (tried also true) in Options of the menu, but a placeholder still does not appear like a gradient

**Screenshots**
![image](https://user-images.githubusercontent.com/62369973/101135057-53551080-361c-11eb-839b-4a7d77d703ff.png)
![image](https://user-images.githubusercontent.com/62369973/101135087-5c45e200-361c-11eb-9501-94979fdb75c9.png)
![image](https://user-images.githubusercontent.com/62369973/101135104-636cf000-361c-11eb-8db7-c6e84ab418f9.png)

**Server Information**
https://hasteb.in/uketemop

**Comment by Arasple** [comment]
This option is in `settings.yml`

**Comment by OfT3N** [comment]
![image](https://user-images.githubusercontent.com/62369973/101142206-57862b80-3626-11eb-82a0-6ff43ccfe874.png)
![image](https://user-images.githubusercontent.com/62369973/101142233-5fde6680-3626-11eb-8975-83c0478e2faa.png)

Doesn't work either (

> This option is in `settings.yml`
