### ISSUE TITLE
/trmenu template does not like colored leather armor

### ISSUE THREAD

**Issue by OfT3N** [TrMenu/TrMenu#253]
**Describe the bug**
/trmenu template does the leather armor color syntax wrongly

**To Reproduce**
1. Make a template with some colored leather armor
2. See 👍 

**Expected behavior**
Colored leather armor

**Screenshots**
![image](https://user-images.githubusercontent.com/62369973/101276772-483ae580-37c0-11eb-9ac2-b3aa6ff5b6a5.png)
![image](https://user-images.githubusercontent.com/62369973/101276776-4ec95d00-37c0-11eb-9d29-9ff80d7af294.png)

**Server Information**
https://hasteb.in/uzosapaj

**Comment by Arasple** [comment]
Will be fixed in v3.0

**Comment by Arasple** [comment]
Will be fixed in v3.0
