### ISSUE TITLE
无法在命令 “/trmenu action <player> <actions...>” 使用条件

### ISSUE THREAD

**Issue by Score2** [TrMenu/TrMenu#258]
[CHAT] This server is running Paper version git-Paper-274 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
 [CHAT] Checking version, please wait...
 [CHAT] Previous version: git-Paper-271 (MC: 1.16.4)
 [CHAT] You are 46 version(s) behind
 [CHAT] PlaceholderAPI (2.10.10-DEV-110)
 [CHAT] Author: [HelpChat]
 [CHAT] PAPI Commands: /papi help
 [CHAT] eCloud Commands: /papi ecloud
 [CHAT]  
 [CHAT]  TrMenu v2.08

**Comment by Arasple** [comment]
Will be fixed in v3.0
