### ISSUE TITLE
Tellraw 和 Tell 的载入时间差别

### ISSUE THREAD

**Issue by Fairy-Bit** [TrMenu/TrMenu#263]
**问题反馈：**
  ![代码截图](https://user-images.githubusercontent.com/74715576/102703761-fa3cdc00-42ad-11eb-8c0b-7de9ae9f399c.png)
  如图所示, 这是我在RegisterCommand中写入的代码
  但是当我到游戏输入指令时, 它却是这样显示的
  ![游戏截图](https://user-images.githubusercontent.com/74715576/102703772-27898a00-42ae-11eb-8733-d283a1e33e51.png)
  即无论我怎么写, 总是载入的总是Tell, 然后才能载入Console的命令

**可能你有个解决办法是**：
  将"Console: tellraw"换成了"Tellraw:"
  如果这样, 那么我的 Json 信息就没法被载入
  只能说TrMenu V2.08还未完全兼容MC原版的Tellraw JSON信息

**Comment by Tanguygab** [comment]
I don't know why it does that but you could try to use delays: https://trmenu.trixey.cc/actions/options/delay

**Comment by Arasple** [comment]
Will be fixed in v3.x
```
    execute:
      - 'tell: &7---------------------------------'
      - 'tellraw: <&3Website@hover=Click\nPls@url=https://trmenu.trixey.cc>'
      - 'tell: &7---------------------------------'
```
