### ISSUE TITLE
Error with ChatControlRed

### ISSUE THREAD

**Issue by Tylwen** [TrMenu/TrMenu#267]
Hello, the plugin (TrMenu & TatooLib) does not work with ChatControlRed. It breaks the connection of PAPI & ChatControlRed.

For more information, I let you see my other post:
https://github.com/kangarko/ChatControl-Red/issues/398

**Comment by Tanguygab** [comment]
So this can be closed I guess?
![image](https://user-images.githubusercontent.com/45695833/104845674-f1542000-58d6-11eb-884d-c60a4032672b.png)
