### ISSUE TITLE
Delete

### ISSUE THREAD

**Issue by Bossbirdyman51** [TrMenu/TrMenu#276]
Can Delete

**Comment by Arasple** [comment]
Do you have any other plugin using Kotlin?

**Comment by Bossbirdyman51** [comment]
I don't know, how to verify if other plugin use kotlin ?

**Comment by Arasple** [comment]
Could you send your plugins list screenshot with the plugin's size, please?

**Comment by Bossbirdyman51** [comment]
I send /pl and a screen ?

**Comment by Bossbirdyman51** [comment]
![image](https://user-images.githubusercontent.com/13882938/105629815-8b6f1780-5e45-11eb-9795-2196ec5821e0.png)
![image](https://user-images.githubusercontent.com/13882938/105629825-99249d00-5e45-11eb-86ba-455c006bbcf0.png)

**Comment by Bossbirdyman51** [comment]
Do you want server log ?

**Comment by Bossbirdyman51** [comment]
New error when i disable 3 other plugin ( Kotlin ) https://pastebin.com/07aVkGP0
