### ISSUE TITLE
Kotlin Library incompatibility

### ISSUE THREAD

**Issue by Angelways** [TrMenu/TrMenu#279]
| TabooLib: 5.48
| TrMenu: 2.08
| AutoRestart:4.2.1 [https://www.spigotmc.org/resources/autorestart.2538/](url)
| CatServer-2a9163f-universal

未安装AutoRestart前运行正常，安装后初次运行报错无法载入所有菜单
[https://paste.ubuntu.com/p/gm6n6zfwbs/](url)

**Comment by Arasple** [comment]
#276
