### ISSUE TITLE
More PAPI Placeholders

### ISSUE THREAD

**Issue by Tanguygab** [TrMenu/TrMenu#74]
Hey Arasple !
So, are you ready for TONS of new placeholders suggestions ? 😂 
Here we go !

**EDITED, CHECK BELOW**

**Comment by Tanguygab** [comment]
fail, wait I edit the message x)

**Comment by Ismael-GT** [comment]
%trmenu_current_item_slot% this is very important, I have like 19 objects repeating the same code, Only change  "+1" for autoincrement. With "%trmenu_current_item_slot%" placeholder I will have only one object in all my .yml 👍

**Comment by Tanguygab** [comment]
I think I'm going to change the syntax of the placeholders tomorrow, to make it more appropriate or better looking, or idk x) just to be better

**Comment by Arasple** [comment]
I don't think Bukkit API nor Minecraft it self provide any way to get the currently hovered item in an inventory

**Comment by Tanguygab** [comment]
🤔then maybe, could you not create a PAPI placeholder for that but just an placeholder built in the plugin only usable in items, and make it replace the value depending on the item where it's used

so if I use placeholders on the item A with the material B, it will replace them for that item

**Comment by Tanguygab** [comment]
Welp, I tried to make it a bit better...

	Built-In placeholders which can only be parsed on items:
- - [ ] `{trmenu_item_identifier_current}` (get the identifier of the current hovered item)
- - [ ] `{trmenu_item_name_current}` (get the name of the current hovered item)
- - [ ] `{trmenu_item_lore_current}` (get the lore of the current hovered item)
- - [ ] `{trmenu_item_slot_current}` (get the slot of the current hovered item)
- - [ ] `{trmenu_item_slots_current}` (get all the slots where the current hovered item is shown)
- - [ ] `{trmenu_item_material_current}` (get the material name of the current hovered item)

	Built-In placeholders which can only be parsed in menus:
- - [ ] `{trmenu_item_name_#}` (get the name of an item from its idenftifier)
- - [ ] `{trmenu_item_lore_#}` (get the lore of an item from its idenftifier)
- - [ ] `{trmenu_item_slot_#}` (get the slot of an item from its idenftifier)
- - [ ] `{trmenu_item_slots_#}` (get all the slots where an item is shown from its idenftifier)
- - [ ] `{trmenu_item_material_#}` (get the material name of an item from its idenftifier)

- - [ ] `{trmenu_menu_identifier_current}` (get the identifier of the current menu)
- - [ ] `{trmenu_menu_title_current}` (get the title of the current menu)
- - [ ] `{trmenu_menu_shape_current}` (get the ID of the current shown shape)
- - [ ] `{trmenu_menu_shapes_current}` (get amount of shapes of the current menu)
- - [ ] `{trmenu_menu_shape_comefrom}` (get the shape where you came from)
- - [ ] `{trmenu_menu_shape_previous}` (get the previous shape in the `Shape:` section)
- - [ ] `{trmenu_menu_shape_next}` (get the next shape in the `Shape:` section)
- - [ ] `{trmenu_menu_dentifier_comefrom}` (get the identifier of the menu where you came from)
- - [ ] `{trmenu_menu_title_comefrom}` (get the title of the menu where you came from)
- - [ ] `{trmenu_menu_shapes_comefrom}` (get amount of shapes of the menu where you came from)
- - [ ] `{trmenu_menu_inputcatcher_comefrom}` (get the input of the menu where you came from)

	PAPI placeholders:
- - [ ] `%trmenu_menus%`
- - [ ] `%trmenu_version%`
- - [ ] `%trmenu_tapapi_<player>|{placeholder}%`
- - [ ] `%trmenu_query_<url>|<query>%`
- - [ ] `%trmenu_menu_identifier_last%` (get the identifier of the last opened menu)
- - [ ] `%trmenu_menu_title_last%` (get the title of the last opened menu)
- - [ ] `%trmenu_menu_shapes_last%`(get the amount of shapes of the last opened menu)
- - [ ] `%trmenu_menu_shape_last%` (get the displayed shape of the last opened menu)
- - [ ] `%trmenu_menu_inputcatcher_last%` (get the input of the last opened menu)

And the actions, they didn't change:
- - [ ] `next-shape` (go to the next shape in the `Shape:` section)
- - [ ] `previous-shape` (go to the previous shape in the `Shape:` section)
- - [ ] `back-shape: [shape]` (go to the shape where you came from. If the player doesn't come from another shape, he will be moved to the defined shape. If it isn't defined, stay on the current shape)
- - [ ] `back-menu: [menu]` (go to the menu where you came from. If the player doesn't come from any menu, he will be moved to the defined menu. If it isn't defined, stay on the current menu)

**Comment by Tanguygab** [comment]
I don't know if you'll do all of that but it's just a suggestion ¯\_(ツ)_/¯ (a BIG suggestion x))

**Comment by Galaxy-VN** [comment]
lmao BIG suggestion xD

**Comment by Tanguygab** [comment]
I've added some new placeholders and also made the ones that I would want the more bold 
Idk if you'll ever do all of them so in case I really want those one, except if it's impossible =/
